import { textifyInLatex } from "../../utils/textifyInLatex";
import { KeyProps } from "./key";

const molecules = [
  { formula: "H_2", name: "Dihydrogène", id: "Dihydrogène" },
  { formula: "O_2", name: "Dioxygène", id: "Dioxygène" },
  { formula: "H_2O", name: "Eau", id: "Eau" },
  { formula: "CH_4", name: "Méthane", id: "Méthane" },
  {
    formula: "CO_2",
    name: "Dioxyde de carbone",
    id: "Dioxyde-de-carbone",
  },
  { formula: "NH_3", name: "Ammoniac", id: "Ammoniac" },
  {
    formula: "SO_2",
    name: "Dioxyde de soufre",
    id: "Dioxyde-de-soufre",
  },
  { formula: "C_2H_5OH", name: "Éthanol", id: "Éthanol" },
  { formula: "C_6H_{12}O_6", name: "Glucose", id: "Glucose" },
  { formula: "CH_3OH", name: "Méthanol", id: "Méthanol" },
  { formula: "C_3H_8", name: "Propane", id: "Propane" },
  { formula: "C_4H_{10}", name: "Butane", id: "Butane" },
  {
    formula: "H_2SO_4",
    name: "Acide sulfurique",
    id: "Acide-sulfurique",
  },
  { formula: "C_2H_4", name: "Éthylène", id: "Éthylène" },
  { formula: "C_3H_6", name: "Propylène", id: "Propylène" },
  { formula: "C_6H_6", name: "Benzène", id: "Benzène" },
  { formula: "CH_3CN", name: "Ammonitrile", id: "Ammonitrile" },
  { formula: "CH_2O", name: "Méthanal", id: "Méthanal" },
  {
    formula: "HCOONa",
    name: "Méthanoate de sodium",
    id: "Méthanoate-de-sodium",
  },
  {
    formula: "CaCO_3",
    name: "Carbonate de calcium",
    id: "Carbonate-de-calcium",
  },
  {
    formula: "(NH_4)_2SO_4",
    name: "Sulfate d'ammonium",
    id: "Sulfate-d'ammonium",
  },
  { formula: "NaOH", name: "Soude caustique", id: "Soude-caustique" },
  {
    formula: "NH_4NO_3",
    name: "Nitrate d'ammonium",
    id: "Nitrate-d'ammonium",
  },
  {
    formula: "Na_2CO_3",
    name: "Carbonate de sodium",
    id: "Carbonate-de-sodium",
  },
  { formula: "C_6H_8O_6", name: "Vitamine C", id: "Vitamine-C" },
  { formula: "C_9H_8O_4", name: "Aspirine", id: "Aspirine" },
  { formula: "C_8H_{10}N_4O_2", name: "Caféine", id: "Caféine" },
  { formula: "C_8H_9NO_2", name: "Paracétamol", id: "Paracétamol" },
  {
    formula: "NaCl",
    name: "Chlorure de sodium",
    id: "Chlorure-de-sodium",
  },
  { formula: "C_{12}H_{22}O_{11}", name: "Lactose", id: "Lactose" },
  { formula: "CH_3COOH", name: "Acide acétique", id: "Acide-acétique" },
  { formula: "Mg", name: "Magnésium", id: "Magnésium" },
  {
    formula: "MgO",
    name: "Oxyde de magnésium",
    id: "Oxyde-de-magnésium",
  },
  { formula: "Fe", name: "Fer", id: "Fer" },
  {
    formula: "Fe_2O_3",
    name: "Oxyde de fer(III)",
    id: "Oxyde-de-fer-III",
  },
  {
    formula: "HCl",
    name: "Acide chlorhydrique",
    id: "Acide-chlorhydrique",
  },
  {
    formula: "NaOH",
    name: "Hydroxyde de sodium",
    id: "Hydroxyde-de-sodium",
  },
  {
    formula: "AgNO_3",
    name: "Nitrate d'argent",
    id: "Nitrate-d'argent",
  },
  {
    formula: "AgCl",
    name: "Chlorure d'argent",
    id: "Chlorure-d'argent",
  },
  {
    formula: "NaNO_3",
    name: "Nitrate de sodium",
    id: "Nitrate-de-sodium",
  },
  {
    formula: "Ca(OH)_2",
    name: "Hydroxyde de calcium",
    id: "Hydroxyde-de-calcium",
  },
  {
    formula: "CaSO_4",
    name: "Sulfate de calcium",
    id: "Sulfate-de-calcium",
  },
  {
    formula: "CuSO_4",
    name: "Sulfate de cuivre",
    id: "Sulfate-de-cuivre",
  },
  {
    formula: "Cu(OH)_2",
    name: "Hydroxyde de cuivre(II)",
    id: "Hydroxyde-de-cuivre-II",
  },
  {
    formula: "Na_2SO_4",
    name: "Sulfate de sodium",
    id: "Sulfate-de-sodium",
  },
  { formula: "Zn", name: "Zinc", id: "Zinc" },
  {
    formula: "ZnCl_2",
    name: "Chlorure de zinc",
    id: "Chlorure-de-zinc",
  },
  {
    formula: "KOH",
    name: "Hydroxyde de potassium",
    id: "Hydroxyde-de-potassium",
  },
  {
    formula: "K_2SO_4",
    name: "Sulfate de potassium",
    id: "Sulfate-de-potassium",
  },
  {
    formula: "H_2O_2",
    name: "Peroxyde d'hydrogène",
    id: "Peroxyde-d'hydrogène",
  },
  {
    formula: "PbCl_2",
    name: "Chlorure de plomb(II)",
    id: "Chlorure-de-plomb-II",
  },
  {
    formula: "KI",
    name: "Iodure de potassium",
    id: "Iodure-de-potassium",
  },
  {
    formula: "PbI_2",
    name: "Iodure de plomb(II)",
    id: "Iodure-de-plomb-II",
  },
  {
    formula: "KCl",
    name: "Chlorure de potassium",
    id: "Chlorure-de-potassium",
  },
  {
    formula: "CH_3COONa",
    name: "Acétate de sodium",
    id: "Acétate-de-sodium",
  },
  { formula: "S", name: "Soufre", id: "Soufre" },
  {
    formula: "Ba(NO_3)_2",
    name: "Nitrate de baryum",
    id: "Nitrate-de-baryum",
  },
  {
    formula: "BaSO_4",
    name: "Sulfate de baryum",
    id: "Sulfate-de-baryum",
  },
  { formula: "Cu", name: "Cuivre", id: "Cuivre" },
  {
    formula: "Cu(NO_3)_2",
    name: "Nitrate de cuivre(II)",
    id: "Nitrate-de-cuivre-II",
  },
  { formula: "Ag", name: "Argent", id: "Argent" },
  {
    formula: "Ca_3(PO_4)_2",
    name: "Phosphate de calcium",
    id: "Phosphate-de-calcium",
  },
  { formula: "S_8", name: "Soufre", id: "Soufre" },
  {
    formula: "KNO_3",
    name: "Nitrate de potassium",
    id: "Nitrate-de-potassium",
  },
  { formula: "N_2", name: "Azote", id: "Azote" },
  {
    formula: "Pb(NO_3)_2",
    name: "Nitrate de plomb(II)",
    id: "Nitrate-de-plomb-II",
  },
  {
    formula: "PbSO_4",
    name: "Sulfate de plomb(II)",
    id: "Sulfate-de-plomb-II",
  },
  { formula: "CaO", name: "Oxyde de calcium", id: "Oxyde-de-calcium" },
  {
    formula: "CuCl_2",
    name: "Chlorure de cuivre(II)",
    id: "Chlorure-de-cuivre-II",
  },
  {
    formula: "FeCl_2",
    name: "Chlorure de fer(II)",
    id: "Chlorure-de-fer-II",
  },
  { formula: "Cl_2", name: "Chlore", id: "Chlore" },
  {
    formula: "N_2O",
    name: "Protoxyde d'azote",
    id: "Protoxyde-d'azote",
  },
  {
    formula: "N_2O_4",
    name: "Peroxyde de dinitrogène",
    id: "Peroxyde-de-dinitrogène",
  },
  { formula: "NO_2", name: "Dioxyde d'azote", id: "Dioxyde-d'azote" },
  {
    formula: "KClO_3",
    name: "Chlorate de potassium",
    id: "Chlorate-de-potassium",
  },
  { formula: "ZnSO_4", name: "Sulfate de zinc", id: "Sulfate-de-zinc" },
  {
    formula: "H_3PO_4",
    name: "Acide phosphorique",
    id: "Acide-phosphorique",
  },
  { formula: "Na_2O", name: "Oxyde de sodium", id: "Oxyde-de-sodium" },
  { formula: "NO", name: "Monoxyde d'azote", id: "Monoxyde-d'azote" },
  {
    formula: "CO",
    name: "Monoxyde de carbone",
    id: "Monoxyde-de-carbone",
  },
  {
    formula: "Fe_3O_4",
    name: "Oxyde de fer(III)",
    id: "Oxyde-de-fer-III",
  },
  {
    formula: "Cu_2S",
    name: "Sulfure de cuivre(I)",
    id: "Sulfure-de-cuivre-I",
  },
  {
    formula: "Cu_2O",
    name: "Oxyde de cuivre(I)",
    id: "Oxyde-de-cuivre-I",
  },
  { formula: "H_3O^+", name: "Ion hydronium", id: "Ion-hydronium" },
  { formula: "SO_4^{2-}", name: "Ion sulfate", id: "Ion-sulfate" },
  { formula: "Fe^{2+}", name: "Ion fer(II)", id: "Ion-fer-II" },
  { formula: "OH^-", name: "Ion hydroxyde", id: "Ion-hydroxyde" },
  { formula: "Ag^+", name: "Ion argent(I)", id: "Ion-argent-I" },
  { formula: "PO_4^{3-}", name: "Ion phosphate", id: "Ion-phosphate" },
  {
    formula: "Ag_3PO_4",
    name: "Phosphate d'argent(I)",
    id: "Phosphate-d'argent-I",
  },
  { formula: "Cu^{2+}", name: "Ion cuivre(II)", id: "Ion-cuivre-II" },
  {
    formula: "CH_3COONa",
    name: "Acétate de sodium",
    id: "Acétate-de-sodium",
  },
  {
    formula: "Ca_3(PO_3)_2",
    name: "Phosphate de calcium",
    id: "Phosphate-de-calcium",
  },
  {
    formula: "NH_4Cl",
    name: "Chlorure d'ammonium",
    id: "Chlorure-d'ammonium",
  },
  { formula: "S_8", name: "Soufre", id: "Soufre" },
  {
    formula: "Mg(OH)_2",
    name: "Hydroxyde de magnésium",
    id: "Hydroxyde-de-magnésium",
  },
  {
    formula: "MgCl_2",
    name: "Chlorure de magnésium",
    id: "Chlorure-de-magnésium",
  },
];

export const moleculesKeysProps = molecules.map((moleculeData): KeyProps => {
  return {
    // id: moleculeData.name.replaceAll(" ", "-").replaceAll("(", " ").replaceAll(")", ""),
    id: moleculeData.name,
    formatedId: moleculeData.id,
    label: textifyInLatex(moleculeData.formula),
    labelType: "tex",
    mathfieldInstructions: { content: textifyInLatex(moleculeData.formula), method: "write" },
    group: "molecules",
  };
});
