import React from "react";
import { MathField } from "../types/types";
import { KeyProps } from "../keyboard/keys/key";
import { ToolbarTabIds } from "../keyboard/toolbar/toolbarTabs";
import { KeyId } from "../keyboard/keys/keyIds";
export type MathInputProps = {
    numericToolbarKeys?: (KeyId | KeyProps)[];
    numericToolbarTabs?: ToolbarTabIds[];
    alphabeticToolbarKeys?: (KeyId | KeyProps)[];
    setMathfieldRef?: (mf: MathField) => void;
    setClearRef?: (f: () => void) => void;
    initialLatex?: string;
    setValue?: (s: string) => void;
    divisionFormat?: "fraction" | "obelus";
    style?: React.CSSProperties;
    size?: "small" | "medium";
    rootElementId?: string;
    fullWidth?: boolean;
};
export declare const MathInput: ({ numericToolbarKeys, numericToolbarTabs, alphabeticToolbarKeys, setValue, setMathfieldRef, setClearRef, style, initialLatex, rootElementId, divisionFormat, size, fullWidth, }: MathInputProps) => JSX.Element;
