import "./style.css";
import { MathInput } from "./mathInput/mathInput";
import { MathInputProps } from "./mathInput/mathInput";
import { KeyProps } from "./keyboard/keys/key";
import { KeysPropsMap } from "./keyboard/keys/keys";
import { allKeysProps } from "./keyboard/keys/keys";
export default MathInput;
export type { KeyProps };
export type { MathInputProps };
export { KeysPropsMap };
export { allKeysProps };
